package com.github.vvlevchenko.dwarf

import java.util.*

enum class Tag(val value: UShort) {
    DW_TAG_null(0u),
    DW_TAG_array_type(0x01u),
    DW_TAG_class_type(0x02u),
    DW_TAG_entry_point(0x03u),
    DW_TAG_enumeration_type(0x04u),
    DW_TAG_formal_parameter(0x05u),
    DW_TAG_imported_declaration(0x08u),
    DW_TAG_label(0x0au),
    DW_TAG_lexical_block(0x0bu),
    DW_TAG_member(0x0du),
    DW_TAG_pointer_type(0x0fu),
    DW_TAG_reference_type(0x10u),
    DW_TAG_compile_unit(0x11u),
    DW_TAG_string_type(0x12u),
    DW_TAG_structure_type(0x13u),
    DW_TAG_subroutine_type(0x15u),
    DW_TAG_typedef(0x16u),
    DW_TAG_union_type(0x17u),
    DW_TAG_unspecified_parameters(0x18u),
    DW_TAG_variant(0x19u),
    DW_TAG_common_block(0x1au),
    DW_TAG_common_inclusion(0x1bu),
    DW_TAG_inheritance(0x1cu),
    DW_TAG_inlined_subroutine(0x1du),
    DW_TAG_module(0x1eu),
    DW_TAG_ptr_to_member_type(0x1fu),
    DW_TAG_set_type(0x20u),
    DW_TAG_subrange_type(0x21u),
    DW_TAG_with_stmt(0x22u),
    DW_TAG_access_declaration(0x23u),
    DW_TAG_base_type(0x24u),
    DW_TAG_catch_block(0x25u),
    DW_TAG_const_type(0x26u),
    DW_TAG_constant(0x27u),
    DW_TAG_enumerator(0x28u),
    DW_TAG_file_type(0x29u),
    DW_TAG_friend(0x2au),
    DW_TAG_namelist(0x2bu),
    DW_TAG_namelist_item(0x2cu),
    DW_TAG_packed_type(0x2du),
    DW_TAG_subprogram(0x2eu),
    DW_TAG_template_type_parameter(0x2fu),
    DW_TAG_template_value_parameter(0x30u),
    DW_TAG_thrown_type(0x31u),
    DW_TAG_try_block(0x32u),
    DW_TAG_variant_part(0x33u),
    DW_TAG_variable(0x34u),
    DW_TAG_volatile_type(0x35u),
    DW_TAG_dwarf_procedure(0x36u),
    DW_TAG_restrict_type(0x37u),
    DW_TAG_interface_type(0x38u),
    DW_TAG_namespace(0x39u),
    DW_TAG_imported_module(0x3au),
    DW_TAG_unspecified_type(0x3bu),
    DW_TAG_partial_unit(0x3cu),
    DW_TAG_imported_unit(0x3du),
    DW_TAG_condition(0x3fu),
    DW_TAG_shared_type(0x40u),
    DW_TAG_type_unit(0x41u),
    DW_TAG_rvalue_reference_type(0x42u),
    DW_TAG_template_alias(0x43u),
    DW_TAG_lo_user(0x4080u),
    DW_TAG_GNU_call_site(0x4109u),
    DW_TAG_GNU_call_site_parameter(0x410au),
    DW_TAG_hi_user(0xffffu)
}

internal val tags = EnumSet.allOf(Tag::class.java)